[package]
name = "jcode-pdf"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"
repository = "https://github.com/jourdanlabs/omniscode"
homepage = "https://github.com/jourdanlabs/omniscode"

[lib]
name = "jcode_pdf"
path = "src/lib.rs"

[dependencies]
anyhow = "1"
pdf-extract = "0.12"
