[package]
name = "jcode-provider-copilot"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT"
repository = "https://github.com/jourdanlabs/omniscode"
homepage = "https://github.com/jourdanlabs/omniscode"

[dependencies]
jcode-message-types = { path = "../jcode-message-types" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
