#ifndef OMNIS_CREDENTIAL_ENVIRONMENT_NAMES_H
#define OMNIS_CREDENTIAL_ENVIRONMENT_NAMES_H

/*
 * Credential, account, provider-endpoint, and external-auth environment
 * variables shipped by the inherited runtime. The PTY sovereignty test plants
 * a fixture-only canary for every name and refuses any read.
 *
 * Keep this as the single cross-language inventory: both C probes consume the
 * macro directly, and verify_runtime.py parses the quoted names.
 */
#define OMNIS_CREDENTIAL_ENVIRONMENT_NAMES(X) \
    X("AI_GATEWAY_API_KEY") \
    X("ANTHROPIC_ADMIN_API_KEY") \
    X("ANTHROPIC_API_KEY") \
    X("ANTIGRAVITY_API_KEY") \
    X("AWS_ACCESS_KEY_ID") \
    X("AWS_BEARER_TOKEN_BEDROCK") \
    X("AWS_CONTAINER_CREDENTIALS_FULL_URI") \
    X("AWS_CONTAINER_CREDENTIALS_RELATIVE_URI") \
    X("AWS_PROFILE") \
    X("AWS_SECRET_ACCESS_KEY") \
    X("AWS_SESSION_TOKEN") \
    X("AWS_SHARED_CREDENTIALS_FILE") \
    X("AWS_WEB_IDENTITY_TOKEN_FILE") \
    X("AZURE_OPENAI_API_KEY") \
    X("AZURE_OPENAI_ENDPOINT") \
    X("BAILIAN_CODING_PLAN_API_KEY") \
    X("BASETEN_API_KEY") \
    X("BEDROCK_API_KEY") \
    X("CELERIS_API_KEY") \
    X("CEREBRAS_API_KEY") \
    X("CHUTES_API_KEY") \
    X("CLAUDE_API_KEY") \
    X("CLAUDE_CODE_OAUTH_TOKEN") \
    X("CODE_ASSIST_ENDPOINT") \
    X("COMPOSIO_API_KEY") \
    X("COMPOSIO_BASE_URL") \
    X("COMPOSIO_GMAIL_AUTH_CONFIG_ID") \
    X("COMPOSIO_GMAIL_CONNECTED_ACCOUNT_ID") \
    X("COMTEGRA_API_KEY") \
    X("COPILOT_GITHUB_TOKEN") \
    X("CORTECS_API_KEY") \
    X("CURSOR_ACCESS_TOKEN") \
    X("CURSOR_API_KEY") \
    X("CURSOR_REFRESH_TOKEN") \
    X("CUSTOM_API_KEY") \
    X("DEEPINFRA_API_KEY") \
    X("DEEPSEEK_API_KEY") \
    X("EXAMPLE_API_KEY") \
    X("FIRMWARE_API_KEY") \
    X("FIREWORKS_API_KEY") \
    X("FPT_API_KEY") \
    X("GEMINI_API_ENDPOINT") \
    X("GEMINI_API_KEY") \
    X("GEMINI_CLIENT_SECRET") \
    X("GH_TOKEN") \
    X("GITHUB_TOKEN") \
    X("GOOGLE_API_KEY") \
    X("GROQ_API_KEY") \
    X("GENERIC_API_KEY") \
    X("HF_TOKEN") \
    X("JADE_API_TOKEN") \
    X("JADE_API_TOKEN_ID") \
    X("JADE_RELAY_TOKEN") \
    X("JADE_RELAY_TOKEN_ID") \
    X("JADE_TOKEN") \
    X("JCODE_ACCOUNT_ID") \
    X("JCODE_ACCOUNT_EMAIL") \
    X("JCODE_ALLOW_CODEX_LEGACY_AUTH") \
    X("JCODE_ANTIGRAVITY_CLIENT_SECRET") \
    X("JCODE_API_KEY") \
    X("JCODE_AUTH_LIFECYCLE_CEREBRAS_API_KEY") \
    X("JCODE_AUTH_LIFECYCLE_LIVE") \
    X("JCODE_AUTH_LIFECYCLE_OPENCODE_API_KEY") \
    X("JCODE_AUTH_LIFECYCLE_SMOKE") \
    X("JCODE_AUTH_LIFECYCLE_STREAM_SMOKE") \
    X("JCODE_AUTH_TIMING") \
    X("JCODE_BING_API_KEY") \
    X("JCODE_BING_API_KEY_ENV") \
    X("JCODE_CLAUDE_AUTH_CODE") \
    X("JCODE_COPILOT_ALLOW_GH_AUTH_TOKEN") \
    X("JCODE_DISCORD_BOT_TOKEN") \
    X("JCODE_GEMINI_FORCE_OAUTH") \
    X("JCODE_JADE_RELAY_TOKEN") \
    X("JCODE_JADE_RELAY_TOKEN_ID") \
    X("JCODE_LIVE_ANTHROPIC_ALLOW_OAUTH") \
    X("JCODE_MEMORY_EMBEDDING_BASE_URL") \
    X("JCODE_NAMED_PROVIDER_PROFILE") \
    X("JCODE_OPENAI_API_BASE") \
    X("JCODE_OPENAI_COMPAT_API_KEY_NAME") \
    X("JCODE_OPENROUTER_API_BASE") \
    X("JCODE_OPENROUTER_API_KEY_NAME") \
    X("JCODE_OPENROUTER_ALLOW_NO_AUTH") \
    X("JCODE_OPENROUTER_AUTH_HEADER") \
    X("JCODE_OPENROUTER_AUTH_HEADER_NAME") \
    X("JCODE_PROVIDER_PROFILE_ACTIVE") \
    X("JCODE_PROVIDER_PROFILE_NAME") \
    X("JCODE_PROVIDER_MY_GATEWAY_API_KEY") \
    X("JCODE_PROVIDER_BAR_API_KEY") \
    X("JCODE_PROVIDER_FOO_API_KEY") \
    X("JCODE_PROVIDER_MY_API_API_KEY") \
    X("JCODE_SAME_PROVIDER_ACCOUNT_FAILOVER") \
    X("JCODE_SUBSCRIPTION_ACTIVE") \
    X("JCODE_TELEGRAM_BOT_TOKEN") \
    X("JCODE_TRUSTED_EXTERNAL_AUTH_SOURCES") \
    X("KIMI_API_KEY") \
    X("LMSTUDIO_API_KEY") \
    X("MINIMAX_API_KEY") \
    X("MINIMAX_CN_API_KEY") \
    X("MISTRAL_API_KEY") \
    X("MOONSHOT_API_KEY") \
    X("MY_GATEWAY_API_KEY") \
    X("NEBIUS_API_KEY") \
    X("NVIDIA_API_KEY") \
    X("OLLAMA_API_KEY") \
    X("OPENAI_ADMIN_API_KEY") \
    X("OPENAI_API_KEY") \
    X("OPENAI_BASE_URL") \
    X("OPENAI_COMPAT_API_KEY") \
    X("OPENCODE_API_KEY") \
    X("OPENCODE_GO_API_KEY") \
    X("OPENROUTER_API_KEY") \
    X("PERPLEXITY_API_KEY") \
    X("PI_OPENAI_KEY") \
    X("SCALEWAY_API_KEY") \
    X("SIDECHAIN_SECRET") \
    X("STACKIT_API_KEY") \
    X("TOGETHER_API_KEY") \
    X("XAI_API_KEY") \
    X("XIAOMI_MIMO_API_KEY") \
    X("ZAI_API_KEY") \
    X("ZHIPU_API_KEY")

#endif
